  # [START gke_boa_kubernetes_manifests_ledger_db_configmap_ledger_db_config]
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ledger-db-config
    labels:
      app: postgres
  data:
    POSTGRES_DB: postgresdb
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
    SPRING_DATASOURCE_URL: jdbc:postgresql://ledger-db:5432/postgresdb
    SPRING_DATASOURCE_USERNAME: admin # should match POSTGRES_USER
    SPRING_DATASOURCE_PASSWORD: password # should match POSTGRES_PASSWORD
  # [END gke_boa_kubernetes_manifests_ledger_db_configmap_ledger_db_config]