---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- accounts-db.yaml
- balance-reader-hpa.yaml
- balance-reader.yaml
- config.yaml
- contacts-hpa.yaml
- contacts.yaml
- frontend-hpa.yaml
- frontend.yaml
- ledger-db.yaml
- ledger-writer-hpa.yaml
- ledger-writer.yaml
- loadgenerator.yaml
- transaction-history-hpa.yaml
- transaction-history.yaml
- userservice-hpa.yaml
- userservice.yaml
